server:
  port: 9090

spring:
  application:
    name: Vocabulary API
  datasource:
    url: jdbc:postgresql://localhost:25432/vocabulary_api
    username: enrico
    password: enrico
  data:
    web:
      pageable:
        max-page-size: 2147483647
  ### oauth2 configuration ###
  security:
    oauth2:
      client:
        registration:
          google :
            clientId: ${google.clientId}
            clientSecret: ${google.clientSecret}

  # Database Flyway migrations
  flyway:
    locations: classpath:/db/migration
    schemas: vocabulary
application:
  api:
    version: v1
    description: ${spring.application.name}
    base-path: /api/${application.api.version}/vocabulary


