spring:
  application:
    name: Vocabulary API
  datasource:
    url: jdbc:postgresql://localhost:25432/vocabulary_api
    username: enrico
    password: enrico

# Database Flyway migrations
  flyway:
    locations: classpath:/db/migration
    schemas: vocabulary
application:
  api:
    version: v1
    description: ${spring.application.name}
    base-path: /api/${application.api.version}/vocabulary
