server:
  port: 9090
  forward-headers-strategy: framework

spring:
  application:
    name: Vocabulary API
  datasource:
    url: jdbc:postgresql://localhost:25432/vocabulary_api
    username: enrico
    password: enrico
  data:
    web:
      pageable:
        max-page-size: 2147483647
  ### oauth2 configuration ###
  security:
    oauth2:
      client:
        registration:
          google :
            clientId: ${google.clientId}
            clientSecret: ${google.clientSecret}
            scope: profile, email
            redirect-uri: "http://localhost:9090/login/oauth2/code/google"
            client-name: vocabulary-localhost

  # Database Flyway migrations
  flyway:
    locations: classpath:/db/migration
    schemas: vocabulary
application:
  api:
    version: v1
    description: ${spring.application.name}
    base-path: /api/${application.api.version}/vocabulary
    admin-path: ${application.api.base-path}/admin
    user-path: ${application.api.base-path}/user
    authenticated-path: ${application.api.base-path}/authenticated
    public-path: ${application.api.base-path}/public


