spring:
  application:
    name: Vocabulary API
  datasource:
    url: jdbc:postgresql://localhost:25432/vocabulary_api
    username: enrico
    password: enrico

# Database Flyway migrations
  flyway:
    locations: classpath:/db/migration
    schemas: vocabulary